### ISSUE TITLE
State put modifies x

### ISSUE THREAD

**Issue by shineli1984** [mattbierner/akh#29]
When execute the example in the README.md, it produce the following result:

```
[ { x: 'state1xyzaa', s: 'state1xyz' },
  { x: '3aa', s: 'new_state' } ]
```

But it should be:
```
[
    {'x': '1aa', 's': 'state1xyz'},
    {'x': '3aa', 's': 'new_state'},
    {'x': '10aa', 's': 'state1xyz'}
    {'x': 'state1xyzaa', 's': 'state1xyz'}
]
```

I think by calling `put` it should only change `s` not `x`

**Comment by mattbierner** [comment]
Thanks for the report.

I've fixed the example with #29 to match the expected behavior. The problem was that `concat` only takes a single argument, not multiple arguments.

---

`put` changing both the value and the state is the intended behavior, but this may be something worth revisiting in the future.

To summarize the core problem: `M.put('state')` has to return a value and state. It's unclear what the value should be if we want to allow the monad to contain any values, so I opted to set the value to the state.

Another API to consider instead would be `M.of(3).put('state')`, which the APIs do not currently support (it currently evaluates to just `M.put('state')`). I'm taking a larger look back at this library and may revisit this, but not with v2.x.  Please let me know if you have any ideas or suggestions here.

Thanks.

**Comment by shineli1984** [comment]
@mattbierner I guess I can always use modify and map together to keep value underneath around.
 
I think if the lib is to mirror the behavior of mtl, put method should set x to an unit value as I remembered. So put should return undefined as underneath value?

**Comment by mattbierner** [comment]
Yes, that would match the behavior of mtl better but seems like a somewhat unnecessary restriction for Javascript. Is there a case where returning undefined is more useful, or is this more about familiarity and expected behavior?

**Comment by shineli1984** [comment]
I couldn't think of an use case right now. So i guess it's more about familiarity or about putting a terminal object there will somehow make better sense as in we don't real care what it is.
